name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        env:
          GITHUB_ACTOR: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PASSWORD }}
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build