name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Gradle file to be executable
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Store JAR name as environment variable
        id: jar-name
        working-directory: build/libs
        run: |
          var1=$(echo $(ls | head -n 1 | sed 's/\.[^.]*$//'))
          echo "ARTIFACT_NAME=$(echo $var1)" >> $GITHUB_OUTPUT
          echo "Stored artifact name as \"$var1\"";
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.jar-name.outputs.ARTIFACT_NAME }}-EXTRACT-ME"
          path: "build/libs/*"
